
[functions.plaid-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/plaid-webhook/deno.json"
entrypoint = "./functions/plaid-webhook/index.ts"

[functions.plaid-sync]
enabled = true
verify_jwt = false
import_map = "./functions/plaid-sync/deno.json"
entrypoint = "./functions/plaid-sync/index.ts"
